# file: xxx/meta/main.yml

galaxy_info:
  author: pjan vandaele
  company: Ansibles
  description: Installs the cron package and starts the crond service
  min_ansible_version: 1.4
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - system

dependencies: []
