# file: cron/tasks/main.yml

- name: Cron | Make sure cron is installed
  apt:
    pkg: cron
    state: present

- name: Cron | Make sure cron is enabled
  service:
    name: cron
    state: restarted
    enabled: yes
