---

- include: install.deb.yml
  when: ansible_os_family == 'Debian'

- name: Ensure RabbitMQ is running
  service: name=rabbitmq-server state=started

- name: Ensure the users is removed
  rabbitmq_user: user={{item}} state=absent
  with_items: rabbitmq_user_remove

- name: Ensure the vhosts is present
  rabbitmq_vhost: name={{item}}
  with_items: rabbitmq_vhosts

- name: Ensure the users is present
  rabbitmq_user: >
      user={{item.user}}
      password={{item.password}}
      configure_priv={{item.configure_priv|default('.*')}}
      read_priv={{item.read_priv|default('.*')}}
      write_priv={{item.write_priv|default('.*')}}
      tags={{item.tags|default('')}}
  with_items: rabbitmq_users

- name: Symlink RabbitMQ bin to sbin
  file: state=link src=/usr/lib/rabbitmq/bin dest=/usr/lib/rabbitmq/sbin

- name: Enable the plugins is installed
  rabbitmq_plugin: names={{item}} state=enabled prefix=/usr/lib/rabbitmq
  with_items: rabbitmq_plugins
  notify:
    - rabbitmq restart
