---
- hosts: all
  roles:
    - Ansibles.postgresql
    - Stouts.redis
    - Stouts.iptables
    - Ansibles.cron
    - Ansibles.git
    - Ansibles.tmpreaper
    - Ansibles.monit
    - Ansibles.perl
    - Stouts.apt
    - Stouts.hostname
    - Stouts.locale
    - Stouts.timezone
    - Ansibles.build-essential
    - Stouts.source
    - Stouts.django
    - Stouts.wale
    - ciupy3
