# file: monit/meta/main.yml

galaxy_info:
  author: pjan vandaele
  company: Ansibles
  description: "Installs monit monitoring and management tool (and attaches it to ssh, cron, ntpd)."
  min_ansible_version: 1.4
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - system
  - monitoring

dependencies: []
