# file: perl/tasks/main.yml

- name: Perl | Get the platform specific variables
  include_vars: "{{ansible_os_family}}.yml"

- name: Perl | Make sure the packages are installed (Debian)
  apt:
    pkg: "{{item}}"
    state: present
  with_items: perl_packages
  when: ansible_os_family == "Debian"

- name: Perl | CPAN | Get the cpan script
  get_url:
    url: "{{perl_cpanm_url}}"
    dest: "{{perl_cpanm_path}}"
    owner: root
    group: root
    mode: 0755
