---

limits_enabled: yes
limits_path: /etc/security/limits.d/tune.conf

# See http://linux.die.net/man/5/limits.conf for description
limits_limits:
  - "*    -    nofile    65535"

limits_sysctl:
  - { name: 'net.ipv4.tcp_tw_recycle',      value: '1' }
  - { name: 'net.ipv4.tcp_tw_reuse',        value: '1' }
