# file: git/meta/main.yml

galaxy_info:
  author: pjan vandaele
  company: Ansibles
  description: Install Git (package, source, server)
  min_ansible_version: 1.4
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - system
  - development

dependencies:
  - Ansibles.build-essential
