---

dependencies: []

galaxy_info:
  author: klen
  company: Stouts
  description: Manage nginx
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - cloud
  - system
  - web
