---

- name: Ensure wale user and group exists
  user: name={{ wale_user }}
- group: name={{ wale_group }}

- name: Ensure wale home is exists
  file: >
    group={{ wale_group }}
    owner={{ wale_user }}
    path={{ item }}
    state=directory
  with_items: [ "{{wale_home}}", "{{wale_logdir}}" ]

- name: Configure wale
  template: >
    dest={{ wale_home }}/wale.sh
    group={{ wale_group }}
    mode=744
    owner={{ wale_user }}
    src=wale.sh.j2

- name: Configure cron
  template: src=cron.j2 dest=/etc/cron.d/wale owner=root group=root mode=0644
